'use client';

import { useEffect, useState } from 'react';
import Image from 'next/image';
import { useLanguage } from '@/lib/i18n/language-context';

type Evidence = 'measured' | 'indicative' | 'not_assessed';
type ProfileRow = { key: string; label: string; proportion: number | null; correct: number; total: number; evidence: Evidence };
type Report = {
  band: { label: string; interpretation: string }; weightedScore: number;
  domains: Array<{ domain: string; label: string; proportion: number; correct: number; total: number }>;
  kpis: { overallReadiness: number; situationalJudgment: number | null; decisionEfficiency: number | null; evidence: Evidence; uncertaintyLabel: string };
  approachProfile: ProfileRow[]; cognitiveProfile: ProfileRow[]; decisionProfile: ProfileRow[];
  timingQuality: { rushedAccuracy: number | null; labouredAccuracy: number | null; sustainableAccuracy: number | null };
  priorityMatrix: Array<{ rank: number; objective: string; observedMastery: number; evidence: Evidence; impact: string; action: string }>;
  coverage: { assessedItems: number; ecoTasks: number };
  studySequence: Array<{ label: string; recommendation: string }>;
  timing: { medianSeconds: number; rushed: number; laboured: number; targetSeconds: number };
  review: Array<{ itemId: string; correct: boolean; misconception: string | null; seconds: number }>;
  preparationTarget: number; targetNote: string;
  progress: { attempt: number; previousScore: number | null; delta: number | null; label: string };
  strengths: Array<{ label: string; category: string; proportion: number; evidence: Evidence; interpretation: string }>;
  metricDefinitions: Record<string, string>; pacingNote: string;
  learner: { fullName: string; reportId: string; assessedAt: string; attempt: number; language: string; pathway: string; validity: string };
  scoreExplanation: string; disclaimer: string; basis: string;
};

const pct = (value: number | null) => value === null ? 'Not assessed' : `${Math.round(value * 100)}%`;
const evidenceLabel = (value: Evidence) => value === 'not_assessed' ? 'Not assessed' : value[0].toUpperCase() + value.slice(1);
const scoreTone = (value: number) => value >= .75 ? '#15803d' : value >= .6 ? '#d97706' : '#dc2626';
const displayedScore = (value: number | null, evidence: Evidence, total = 0) => evidence === 'indicative' && total < 5 ? 'More evidence needed' : pct(value);

function EvidenceBadge({ value }: { value: Evidence }) {
  const tone = value === 'measured' ? 'bg-emerald-50 text-emerald-700' : value === 'indicative' ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-500';
  return <span className={`rounded-full px-2 py-1 text-[11px] font-semibold ${tone}`}>{evidenceLabel(value)}</span>;
}

function Track({ value, target, indicative = false }: { value: number; target: number; indicative?: boolean }) {
  return <div className="relative h-3 rounded-full bg-slate-100"><div className="h-3 rounded-full" style={{ width: indicative ? '100%' : `${value * 100}%`, background: indicative ? 'repeating-linear-gradient(135deg,#fef3c7 0 5px,#fffbeb 5px 10px)' : scoreTone(value), border: indicative ? '1px solid #f59e0b' : undefined }} /><span className="absolute -top-1 h-5 w-px bg-slate-900" style={{ left: `${target * 100}%` }} /></div>;
}

function Profile({ rows, target }: { rows: ProfileRow[]; target: number }) {
  return <div className="mt-4 space-y-4">{rows.map((row) => <div key={row.key}><div className="mb-1 flex items-center justify-between gap-3 text-sm"><span>{row.label}</span><span className="flex items-center gap-2"><EvidenceBadge value={row.evidence} /><b>{displayedScore(row.proportion, row.evidence, row.total)}</b></span></div><Track value={row.proportion || 0} target={target} indicative={row.evidence === 'indicative'} /><div className="mt-1 text-xs text-slate-400">{row.total ? `${row.correct}/${row.total} assessed items` : 'No tagged items in this form'}</div></div>)}</div>;
}

function Radar({ rows }: { rows: ProfileRow[] }) {
  const center = 100, radius = 70;
  const point = (index: number, scale: number) => { const angle = -Math.PI / 2 + index * Math.PI * 2 / rows.length; return `${center + radius * scale * Math.cos(angle)},${center + radius * scale * Math.sin(angle)}`; };
  return <div className="mt-3"><svg viewBox="0 0 200 200" className="mx-auto h-52 w-52" role="img" aria-label="Delivery approach radar chart">{[.33, .66, 1].map((scale) => <g key={scale}><polygon points={rows.map((_, index) => point(index, scale)).join(' ')} fill="none" stroke="#d8dbe8" /><text x="103" y={100-radius*scale+3} className="fill-slate-400 text-[6px]">{Math.round(scale*100)}</text></g>)}<polygon points={rows.map((row, index) => point(index, row.proportion || 0)).join(' ')} fill="rgba(8,173,173,.18)" stroke="#08adad" strokeWidth="3" />{rows.map((row, index) => { const [x, y] = point(index, 1.22).split(','); return <text key={row.key} x={x} y={y} textAnchor="middle" className="fill-slate-600 text-[9px]">{row.label}</text>; })}</svg></div>;
}

export default function ReportClient() {
  const { isArabic } = useLanguage();
  const [report, setReport] = useState<Report | null>(null); const [error, setError] = useState('');
  useEffect(() => { fetch('/api/diagnostic/report').then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setReport(data.report); }).catch((cause) => setError(cause.message || 'Report unavailable')); }, []);
  if (error) return <main className="min-h-screen grid place-items-center p-5 text-red-700">{error}</main>;
  if (!report) return <main className="min-h-screen grid place-items-center p-5 text-slate-600">{isArabic ? 'جارٍ إعداد التقرير…' : 'Preparing report…'}</main>;
  const gap = Math.max(0, Math.round((report.preparationTarget - report.kpis.overallReadiness) * 100)); const incorrect = report.review.filter((item) => !item.correct);
  return <main dir={isArabic ? 'rtl' : 'ltr'} className="relative min-h-screen overflow-hidden bg-[#f4f3fb] px-4 py-8 text-slate-900"><Image src="/brand/pmpeco-watermark.png" alt="" width={620} height={620} className="pointer-events-none fixed -bottom-24 -right-24 opacity-[0.04]" /><div className="relative mx-auto max-w-5xl space-y-6">
    <header className="rounded-3xl p-8 text-white shadow-sm" style={{ background: 'linear-gradient(90deg,#320f91 0%,#244bab 50%,#00aeae 100%)' }}><div className="flex items-center gap-4"><Image src="/brand/pmpeco-white-logo.png" alt="PMPeco" width={64} height={64}/><div><div className="text-sm font-bold text-white/90">PMPeco</div><h1 className="mt-1 text-3xl font-bold">{isArabic ? 'تقرير تشخيص الجاهزية لاختبار PMP' : 'PMP Readiness Diagnostic'}</h1></div></div><div className="mt-6 inline-flex rounded-full bg-white/15 px-4 py-2 font-semibold">{report.band.label}</div><p className="mt-4 max-w-3xl leading-7 text-white/90">{report.band.interpretation}</p></header>
    <section className="rounded-2xl border border-violet-100 bg-white p-6"><h2 className="text-xl font-bold text-violet-950">Learner and assessment details</h2><dl className="mt-4 grid gap-x-8 gap-y-4 sm:grid-cols-2 lg:grid-cols-3">{[['Full name',report.learner.fullName],['Report ID',report.learner.reportId],['Assessment date',new Date(report.learner.assessedAt).toLocaleString()],['Attempt',String(report.learner.attempt)],['Language',report.learner.language],['PMP pathway',report.learner.pathway]].map(([label,value])=><div key={label}><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className={`mt-1 text-slate-900 ${label === 'Full name' ? 'text-2xl font-bold uppercase text-slate-600' : 'font-medium'}`}>{value}</dd></div>)}</dl><p className="mt-5 border-t border-slate-100 pt-4 text-xs text-slate-500">{report.learner.validity}</p></section>
    <section className="rounded-2xl border border-violet-100 bg-white p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-xs font-semibold uppercase text-slate-500">Overall readiness</div><div className="mt-1 text-4xl font-bold" style={{color:scoreTone(report.kpis.overallReadiness)}}>{pct(report.kpis.overallReadiness)}</div></div><div className="text-right text-xs text-slate-500">Guideline {pct(report.preparationTarget)}<br/>{report.progress.label}</div></div><div className="mt-4"><Track value={report.kpis.overallReadiness} target={report.preparationTarget}/></div><p className="mt-3 text-sm text-slate-600">{report.scoreExplanation} Current distance to the preparation guideline: {gap} points.</p><p className="mt-1 text-xs text-slate-400">{report.targetNote}</p><div className="mt-5 grid gap-4 sm:grid-cols-3">{[['Situational judgment',pct(report.kpis.situationalJudgment),'situationalJudgment'],['Decision efficiency',pct(report.kpis.decisionEfficiency),'decisionEfficiency'],['Measurement confidence',report.kpis.uncertaintyLabel,'measurementConfidence']].map(([label,value,key])=><div key={key} className="rounded-xl bg-violet-50 p-4"><div className="text-xs font-semibold uppercase text-slate-500">{label}</div><div className="mt-2 text-xl font-bold text-violet-900">{value}</div><p className="mt-2 text-xs leading-5 text-slate-500">{report.metricDefinitions[key]}</p></div>)}</div></section>
    <section className="rounded-2xl border border-emerald-100 bg-white p-6"><h2 className="text-xl font-bold text-violet-950">Your strengths</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{report.strengths.map((s)=><div key={`${s.category}-${s.label}`} className="rounded-xl bg-emerald-50 p-4"><div className="text-xs font-semibold uppercase text-emerald-700">{s.category}</div><div className="mt-1 font-bold">{s.label} · {pct(s.proportion)}</div><p className="mt-2 text-sm text-slate-600">{s.interpretation}</p></div>)}</div></section>
    <section className="rounded-2xl border border-violet-100 bg-white p-6"><h2 className="text-xl font-bold text-violet-950">ECO domain performance</h2><div className="mt-5 space-y-5">{report.domains.map((d)=>{const ev:Evidence=d.total>=5?'measured':d.total?'indicative':'not_assessed';return <div key={d.domain}><div className="mb-2 flex justify-between text-sm"><span>{d.label}</span><span>{displayedScore(d.proportion,ev,d.total)} ({d.correct}/{d.total})</span></div><Track value={d.proportion} target={report.preparationTarget} indicative={ev==='indicative'}/></div>})}</div></section>
    <section className="grid gap-6 md:grid-cols-3"><div className="rounded-2xl border border-violet-100 bg-white p-6"><h2 className="font-bold text-violet-950">Delivery approach agility</h2><Radar rows={report.approachProfile}/><p className="text-xs leading-5 text-slate-500">{report.metricDefinitions.deliveryApproach}</p></div><div className="rounded-2xl border border-violet-100 bg-white p-6"><h2 className="font-bold text-violet-950">Cognitive depth</h2><Profile rows={report.cognitiveProfile} target={report.preparationTarget}/><p className="mt-3 text-xs leading-5 text-slate-500">{report.metricDefinitions.cognitiveDepth}</p></div><div className="rounded-2xl border border-violet-100 bg-white p-6"><h2 className="font-bold text-violet-950">Decision priority</h2><Profile rows={report.decisionProfile} target={report.preparationTarget}/><p className="mt-3 text-xs leading-5 text-slate-500">{report.metricDefinitions.decisionPriority}</p></div></section>
    <section className="rounded-2xl border border-violet-100 bg-white p-6"><h2 className="text-xl font-bold text-violet-950">Top learning priorities</h2><div className="mt-4 space-y-3">{report.priorityMatrix.map((row)=><div key={row.objective} className="grid gap-2 rounded-xl border border-slate-100 p-4 md:grid-cols-[40px_1fr_2fr]"><b className="text-violet-900">{row.rank}</b><div><b>{row.objective}</b><div className="mt-2"><EvidenceBadge value={row.evidence}/></div></div><p className="text-sm text-slate-600">{row.action}</p></div>)}</div></section>
    <section className="grid gap-6 md:grid-cols-2"><div className="rounded-2xl border border-violet-100 bg-white p-6"><h2 className="text-xl font-bold text-violet-950">Timing quality</h2><div className="mt-4 grid grid-cols-3 gap-3 text-center"><div className="rounded-xl bg-violet-50 p-4"><b>{report.timing.medianSeconds}s</b><div className="text-xs text-slate-500">Median</div></div><div className="rounded-xl bg-violet-50 p-4"><b>{report.timing.rushed>=5?pct(report.timingQuality.rushedAccuracy):'More evidence needed'}</b><div className="text-xs text-slate-500">Rushed · n={report.timing.rushed}</div></div><div className="rounded-xl bg-violet-50 p-4"><b>{report.timing.laboured>=5?pct(report.timingQuality.labouredAccuracy):'More evidence needed'}</b><div className="text-xs text-slate-500">Laboured · n={report.timing.laboured}</div></div></div><p className="mt-3 text-xs leading-5 text-slate-500">{report.pacingNote}</p></div><div className="rounded-2xl border border-violet-100 bg-white p-6"><h2 className="text-xl font-bold text-violet-950">Recommended readiness path</h2><ol className="mt-4 space-y-3">{report.studySequence.map((s,i)=><li key={s.label} className="text-sm"><b>{i+1}.</b> {s.recommendation}</li>)}</ol><a href="/dashboard" className="mt-5 block rounded-xl bg-gradient-to-r from-violet-700 to-teal-600 px-5 py-4 text-center font-semibold text-white">Start my readiness plan</a></div></section>
    <section className="rounded-2xl border border-violet-100 bg-white p-6"><h2 className="text-xl font-bold text-violet-950">Misconceptions to correct</h2><p className="mt-2 text-sm text-slate-500">The answer key is protected. Each pattern points you toward targeted learning and practice.</p><div className="mt-4 space-y-2">{incorrect.map((item,i)=><div key={item.itemId} className="rounded-lg bg-red-50 p-3 text-sm text-red-800"><b>{i+1}.</b> {item.misconception} <a href="/dashboard/practice" className="font-semibold underline">Practice this skill</a></div>)}</div></section>
    <a href="/api/diagnostic/report/pdf" className="block rounded-xl bg-gradient-to-r from-violet-700 to-teal-600 px-5 py-4 text-center font-semibold text-white">Download branded, watermarked PDF report</a>
    <footer className="space-y-2 pb-8 text-xs leading-5 text-slate-500"><p>{report.basis}</p><p>{report.disclaimer}</p><p>Measured = 5+ relevant items. Indicative results use a visibly different treatment and suppress fragile percentages when fewer than five items are available.</p></footer>
  </div></main>;
}
