'use client';

import { useEffect, useState } from 'react';
import Image from 'next/image';
import { useLanguage } from '@/lib/i18n/language-context';

type Evidence = 'measured' | 'indicative' | 'not_assessed';
type ProfileRow = { key: string; label: string; proportion: number | null; correct: number; total: number; evidence: Evidence };
type Report = {
  band: { label: string; interpretation: string }; weightedScore: number;
  domains: Array<{ domain: string; label: string; proportion: number; correct: number; total: number }>;
  kpis: { overallReadiness: number; situationalJudgment: number | null; decisionEfficiency: number | null; evidence: Evidence; uncertaintyLabel: string };
  approachProfile: ProfileRow[]; cognitiveProfile: ProfileRow[]; decisionProfile: ProfileRow[];
  timingQuality: { rushedAccuracy: number | null; labouredAccuracy: number | null; sustainableAccuracy: number | null };
  priorityMatrix: Array<{ rank: number; objective: string; observedMastery: number; evidence: Evidence; impact: string; action: string }>;
  coverage: { assessedItems: number; ecoTasks: number };
  studySequence: Array<{ label: string; recommendation: string }>;
  timing: { medianSeconds: number; rushed: number; laboured: number; targetSeconds: number };
  review: Array<{ itemId: string; correct: boolean; misconception: string | null; seconds: number }>;
  preparationTarget: number; targetNote: string;
  progress: { attempt: number; previousScore: number | null; delta: number | null; label: string };
  strengths: Array<{ label: string; category: string; proportion: number; evidence: Evidence; interpretation: string }>;
  metricDefinitions: Record<string, string>; pacingNote: string;
  learner: { fullName: string; reportId: string; assessedAt: string; attempt: number; language: string; pathway: string; validity: string };
  scoreExplanation: string; disclaimer: string; basis: string;
};

const pct = (value: number | null, ar = false) => value === null ? (ar ? 'غير مقاس' : 'Not assessed') : `${Math.round(value * 100)}%`;
const evidenceLabel = (value: Evidence, ar = false) => ar ? ({ measured: 'مقاس', indicative: 'استرشادي', not_assessed: 'غير مقاس' }[value]) : value === 'not_assessed' ? 'Not assessed' : value[0].toUpperCase() + value.slice(1);
const scoreTone = (value: number) => value >= .75 ? '#15803d' : value >= .6 ? '#d97706' : '#dc2626';
const displayedScore = (value: number | null, evidence: Evidence, total = 0, ar = false) => evidence === 'indicative' && total < 5 ? (ar ? 'يلزم مزيد من الأدلة' : 'More evidence needed') : pct(value, ar);

function EvidenceBadge({ value, ar = false }: { value: Evidence; ar?: boolean }) {
  const tone = value === 'measured' ? 'bg-emerald-50 text-emerald-700' : value === 'indicative' ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-500';
  return <span className={`rounded-full px-2 py-1 text-[11px] font-semibold ${tone}`}>{evidenceLabel(value, ar)}</span>;
}

function Track({ value, target, indicative = false }: { value: number; target: number; indicative?: boolean }) {
  return <div className="relative h-3 rounded-full bg-slate-100"><div className="h-3 rounded-full" style={{ width: indicative ? '100%' : `${value * 100}%`, background: indicative ? 'repeating-linear-gradient(135deg,#fef3c7 0 5px,#fffbeb 5px 10px)' : scoreTone(value), border: indicative ? '1px solid #f59e0b' : undefined }} /><span className="absolute -top-1 h-5 w-px bg-slate-900" style={{ left: `${target * 100}%` }} /></div>;
}

function Profile({ rows, target, ar = false }: { rows: ProfileRow[]; target: number; ar?: boolean }) {
  return <div className="mt-4 space-y-4">{rows.map((row) => <div key={row.key}><div className="mb-1 flex items-center justify-between gap-3 text-sm"><span>{row.label}</span><span className="flex items-center gap-2"><EvidenceBadge value={row.evidence} ar={ar} /><b>{displayedScore(row.proportion, row.evidence, row.total, ar)}</b></span></div><Track value={row.proportion || 0} target={target} indicative={row.evidence === 'indicative'} /><div className="mt-1 text-xs text-slate-400">{row.total ? (ar ? `${row.correct}/${row.total} من البنود المقاسة` : `${row.correct}/${row.total} assessed items`) : (ar ? 'لا توجد بنود مصنفة في هذا النموذج' : 'No tagged items in this form')}</div></div>)}</div>;
}

function Radar({ rows, ar = false }: { rows: ProfileRow[]; ar?: boolean }) {
  const center = 100, radius = 70;
  const point = (index: number, scale: number) => { const angle = -Math.PI / 2 + index * Math.PI * 2 / rows.length; return `${center + radius * scale * Math.cos(angle)},${center + radius * scale * Math.sin(angle)}`; };
  return <div className="mt-3"><svg viewBox="0 0 200 200" className="mx-auto h-52 w-52" role="img" aria-label={ar ? 'مخطط راداري لمناهج التسليم' : 'Delivery approach radar chart'}>{[.33, .66, 1].map((scale) => <g key={scale}><polygon points={rows.map((_, index) => point(index, scale)).join(' ')} fill="none" stroke="#d8dbe8" /><text x="103" y={100-radius*scale+3} className="fill-slate-400 text-[6px]">{Math.round(scale*100)}</text></g>)}<polygon points={rows.map((row, index) => point(index, row.proportion || 0)).join(' ')} fill="rgba(8,173,173,.18)" stroke="#08adad" strokeWidth="3" />{rows.map((row, index) => { const [x, y] = point(index, 1.22).split(','); return <text key={row.key} x={x} y={y} textAnchor="middle" className="fill-slate-600 text-[9px]">{row.label}</text>; })}</svg></div>;
}

export default function ReportClient() {
  const { isArabic } = useLanguage();
  const [report, setReport] = useState<Report | null>(null); const [error, setError] = useState('');
  const [returnTo, setReturnTo] = useState('/');
  useEffect(() => {
    setReturnTo(sessionStorage.getItem('pmpeco_diagnostic_return_to') || '/');
    void fetch('/api/diagnostic/event', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ eventName: 'report_view', source: 'report', path: window.location.pathname }) });
    fetch('/api/diagnostic/report').then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setReport(data.report); }).catch((cause) => setError(cause.message || 'Report unavailable'));
  }, []);
  if (error) return <main className="min-h-screen grid place-items-center p-5 text-red-700">{error}</main>;
  if (!report) return <main className="min-h-screen grid place-items-center p-5 text-slate-600">{isArabic ? 'جارٍ إعداد التقرير…' : 'Preparing report…'}</main>;
  const reportArabic = report.learner.language === 'العربية';
  const gap = Math.max(0, Math.round((report.preparationTarget - report.kpis.overallReadiness) * 100)); const incorrect = report.review.filter((item) => !item.correct);
  const t = (en: string, ar: string) => reportArabic ? ar : en;
  return <main dir={reportArabic ? 'rtl' : 'ltr'} className="relative min-h-screen overflow-hidden bg-[#f4f3fb] px-4 py-8 text-slate-900"><Image src="/brand/pmpeco-watermark.png" alt="" width={620} height={620} className="pointer-events-none fixed -bottom-24 -right-24 opacity-[0.04]" /><div className="relative mx-auto max-w-5xl space-y-6">
    <header className="rounded-3xl p-8 text-white shadow-sm" style={{ background: 'linear-gradient(90deg,#320f91 0%,#244bab 50%,#00aeae 100%)' }}><div className="flex items-center gap-4"><Image src="/brand/pmpeco-white-logo.png" alt="PMPeco" width={64} height={64}/><div><div className="text-sm font-bold text-white/90">PMPeco</div><h1 className="mt-1 text-3xl font-bold">{reportArabic ? 'تقرير تشخيص الجاهزية لاختبار PMP' : 'PMP Readiness Diagnostic'}</h1></div></div><div className="mt-6 inline-flex rounded-full bg-white/15 px-4 py-2 font-semibold">{report.band.label}</div><p className="mt-4 max-w-3xl leading-7 text-white/90">{report.band.interpretation}</p></header>
    <section className="rounded-2xl border border-violet-100 bg-white p-6"><h2 className="text-xl font-bold text-violet-950">{t('Learner and assessment details','بيانات المتعلم والتقييم')}</h2><dl className="mt-4 grid gap-x-8 gap-y-4 sm:grid-cols-2 lg:grid-cols-3">{[[t('Full name','الاسم الكامل'),report.learner.fullName],[t('Report ID','رقم التقرير'),report.learner.reportId],[t('Assessment date','تاريخ التقييم'),new Date(report.learner.assessedAt).toLocaleString(reportArabic?'ar':'en')],[t('Attempt','المحاولة'),String(report.learner.attempt)],[t('Language','اللغة'),report.learner.language],[t('PMP pathway','مسار PMP'),report.learner.pathway]].map(([label,value],index)=><div key={label}><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className={`mt-1 text-slate-900 ${index===0?'text-2xl font-bold uppercase text-slate-600':'font-medium'}`}>{value}</dd></div>)}</dl><p className="mt-5 border-t border-slate-100 pt-4 text-xs text-slate-500">{report.learner.validity}</p></section>
    <section className="rounded-2xl border border-violet-100 bg-white p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-xs font-semibold uppercase text-slate-500">{t('Overall readiness','الجاهزية العامة')}</div><div className="mt-1 text-4xl font-bold" style={{color:scoreTone(report.kpis.overallReadiness)}}>{pct(report.kpis.overallReadiness,reportArabic)}</div></div><div className="text-xs text-slate-500">{t('Guideline','المؤشر الاسترشادي')} {pct(report.preparationTarget,reportArabic)}<br/>{report.progress.label}</div></div><div className="mt-4"><Track value={report.kpis.overallReadiness} target={report.preparationTarget}/></div><p className="mt-3 text-sm text-slate-600">{report.scoreExplanation} {t(`Current distance to the preparation guideline: ${gap} points.`,`الفارق الحالي عن مؤشر الإعداد الاسترشادي: ${gap} نقطة.`)}</p><p className="mt-1 text-xs text-slate-400">{report.targetNote}</p><div className="mt-5 grid gap-4 sm:grid-cols-3">{[[t('Situational judgment','الحكم الموقفي'),pct(report.kpis.situationalJudgment,reportArabic),'situationalJudgment'],[t('Decision efficiency','كفاءة القرار'),pct(report.kpis.decisionEfficiency,reportArabic),'decisionEfficiency'],[t('Measurement confidence','الثقة في القياس'),report.kpis.uncertaintyLabel,'measurementConfidence']].map(([label,value,key])=><div key={key} className="rounded-xl bg-violet-50 p-4"><div className="text-xs font-semibold uppercase text-slate-500">{label}</div><div className="mt-2 text-xl font-bold text-violet-900">{value}</div><p className="mt-2 text-xs leading-5 text-slate-500">{report.metricDefinitions[key]}</p></div>)}</div></section>
    <section className="rounded-2xl border border-emerald-100 bg-white p-6"><h2 className="text-xl font-bold text-violet-950">{t('Your strengths','نقاط قوتك')}</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{report.strengths.map((s)=><div key={`${s.category}-${s.label}`} className="rounded-xl bg-emerald-50 p-4"><div className="text-xs font-semibold uppercase text-emerald-700">{s.category}</div><div className="mt-1 font-bold">{s.label} · {pct(s.proportion,reportArabic)}</div><p className="mt-2 text-sm text-slate-600">{s.interpretation}</p></div>)}</div></section>
    <section className="rounded-2xl border border-violet-100 bg-white p-6"><h2 className="text-xl font-bold text-violet-950">{t('ECO domain performance','الأداء حسب محاور ECO')}</h2><div className="mt-5 space-y-5">{report.domains.map((d)=>{const ev:Evidence=d.total>=5?'measured':d.total?'indicative':'not_assessed';return <div key={d.domain}><div className="mb-2 flex justify-between text-sm"><span>{d.label}</span><span>{displayedScore(d.proportion,ev,d.total,reportArabic)} ({d.correct}/{d.total})</span></div><Track value={d.proportion} target={report.preparationTarget} indicative={ev==='indicative'}/></div>})}</div></section>
    <section className="grid gap-6 md:grid-cols-3"><div className="rounded-2xl border border-violet-100 bg-white p-6"><h2 className="font-bold text-violet-950">{t('Delivery approach agility','المرونة عبر مناهج التسليم')}</h2><Radar rows={report.approachProfile} ar={reportArabic}/><p className="text-xs leading-5 text-slate-500">{report.metricDefinitions.deliveryApproach}</p></div><div className="rounded-2xl border border-violet-100 bg-white p-6"><h2 className="font-bold text-violet-950">{t('Cognitive depth','العمق المعرفي')}</h2><Profile rows={report.cognitiveProfile} target={report.preparationTarget} ar={reportArabic}/><p className="mt-3 text-xs leading-5 text-slate-500">{report.metricDefinitions.cognitiveDepth}</p></div><div className="rounded-2xl border border-violet-100 bg-white p-6"><h2 className="font-bold text-violet-950">{t('Decision priority','أولوية القرار')}</h2><Profile rows={report.decisionProfile} target={report.preparationTarget} ar={reportArabic}/><p className="mt-3 text-xs leading-5 text-slate-500">{report.metricDefinitions.decisionPriority}</p></div></section>
    <section className="rounded-2xl border border-violet-100 bg-white p-6"><h2 className="text-xl font-bold text-violet-950">{t('Top learning priorities','أهم أولويات التعلم')}</h2><div className="mt-4 space-y-3">{report.priorityMatrix.map((row)=><div key={row.objective} className="grid gap-2 rounded-xl border border-slate-100 p-4 md:grid-cols-[40px_1fr_2fr]"><b className="text-violet-900">{row.rank}</b><div><b>{row.objective}</b><div className="mt-2"><EvidenceBadge value={row.evidence} ar={reportArabic}/></div></div><p className="text-sm text-slate-600">{row.action}</p></div>)}</div></section>
    <section className="grid gap-6 md:grid-cols-2"><div className="rounded-2xl border border-violet-100 bg-white p-6"><h2 className="text-xl font-bold text-violet-950">{t('Timing quality','جودة إدارة الوقت')}</h2><div className="mt-4 grid grid-cols-3 gap-3 text-center"><div className="rounded-xl bg-violet-50 p-4"><b>{report.timing.medianSeconds}{t('s',' ث')}</b><div className="text-xs text-slate-500">{t('Median','الوسيط')}</div></div><div className="rounded-xl bg-violet-50 p-4"><b>{report.timing.rushed>=5?pct(report.timingQuality.rushedAccuracy,reportArabic):t('More evidence needed','يلزم مزيد من الأدلة')}</b><div className="text-xs text-slate-500">{t('Rushed','متسرعة')} · n={report.timing.rushed}</div></div><div className="rounded-xl bg-violet-50 p-4"><b>{report.timing.laboured>=5?pct(report.timingQuality.labouredAccuracy,reportArabic):t('More evidence needed','يلزم مزيد من الأدلة')}</b><div className="text-xs text-slate-500">{t('Laboured','متأنية جداً')} · n={report.timing.laboured}</div></div></div><p className="mt-3 text-xs leading-5 text-slate-500">{report.pacingNote}</p></div><div className="rounded-2xl border border-violet-100 bg-white p-6"><h2 className="text-xl font-bold text-violet-950">{t('Recommended readiness path','مسار الجاهزية الموصى به')}</h2><ol className="mt-4 space-y-3">{report.studySequence.map((s,i)=><li key={s.label} className="text-sm"><b>{i+1}.</b> {s.recommendation}</li>)}</ol><a href="/dashboard" className="mt-5 block rounded-xl bg-gradient-to-r from-violet-700 to-teal-600 px-5 py-4 text-center font-semibold text-white">{t('Start my readiness plan','ابدأ خطة جاهزيتي')}</a></div></section>
    <section className="rounded-2xl border border-violet-100 bg-white p-6"><h2 className="text-xl font-bold text-violet-950">{t('Misconceptions to correct','المفاهيم الخاطئة المطلوب تصحيحها')}</h2><p className="mt-2 text-sm text-slate-500">{t('The answer key is protected. Each pattern points you toward targeted learning and practice.','مفتاح الإجابة محمي. يوجهك كل نمط إلى تعلم وتدريب محددين.')}</p><div className="mt-4 space-y-2">{incorrect.map((item,i)=><div key={item.itemId} className="rounded-lg bg-red-50 p-3 text-sm text-red-800"><b>{i+1}.</b> {item.misconception} <a href="/dashboard/practice" className="font-semibold underline">{t('Practice this skill','تدرّب على هذه المهارة')}</a></div>)}</div></section>
    <a href="/api/diagnostic/report/pdf" className="block rounded-xl bg-gradient-to-r from-violet-700 to-teal-600 px-5 py-4 text-center font-semibold text-white">{t('Download branded, watermarked PDF report','نزّل تقرير PDF بهوية PMPeco وعلامة مائية')}</a>
    <a href={returnTo} className="block text-center text-sm font-semibold text-violet-800 underline">{t('Return to where I was','العودة إلى الصفحة السابقة')}</a>
    <footer className="space-y-2 pb-8 text-xs leading-5 text-slate-500"><p>{report.basis}</p><p>{report.disclaimer}</p><p>{t('Measured = 5+ relevant items. Indicative results use a visibly different treatment and suppress fragile percentages when fewer than five items are available.','مقاس = خمسة بنود ذات صلة أو أكثر. تُعرض النتائج الاسترشادية بصورة مختلفة بوضوح، وتُحجب النسب غير المستقرة عندما يقل عدد البنود عن خمسة.')}</p></footer>
  </div></main>;
}
