export interface PmpArtifact {
  id: string
  name: string
  category: string
  description: string
  createdBy: string
  whenUsed: string
  keyPurpose: string
  examTip: string
  relatedTo: string[]
  domains: string[]
}

export const ARTIFACT_CATEGORIES = [
  { id: 'strategy', label: '🎯 Strategy', color: '#7c3aed', description: 'Created at project start, rarely change' },
  { id: 'logs', label: '📋 Logs & Registers', color: '#059669', description: 'Continuously updated throughout the project' },
  { id: 'plans', label: '📝 Plans', color: '#2563eb', description: 'Define how work will be managed' },
  { id: 'baselines', label: '📏 Baselines', color: '#d97706', description: 'Approved versions used for comparison' },
  { id: 'visual', label: '📊 Visual & Data', color: '#dc2626', description: 'Charts, diagrams, and hierarchies' },
  { id: 'other', label: '📄 Other Key Documents', color: '#0891b2', description: 'Deliverables, reports, and outputs' },
]

export const PMP_ARTIFACTS: PmpArtifact[] = [
  // ─── STRATEGY ARTIFACTS ────────────────────────────────────────
  {
    id: 'business-case',
    name: 'Business Case',
    category: 'strategy',
    description: 'A value proposition for the proposed project that may include financial and nonfinancial benefits. Justifies why the project should be undertaken.',
    createdBy: 'Project sponsor or business analyst (before the project formally starts)',
    whenUsed: 'Before project initiation — used to evaluate whether the project is worth doing. Referenced throughout to confirm continued alignment with business value.',
    keyPurpose: 'Justifies the investment and serves as the foundation for the project charter.',
    examTip: 'The business case is NOT created by the PM. It exists BEFORE the charter. The PM references it but doesn\'t own it. It\'s an input to Develop Project Charter.',
    relatedTo: ['Project Charter', 'Benefits Management Plan'],
    domains: ['Stakeholders', 'Planning'],
  },
  {
    id: 'project-charter',
    name: 'Project Charter',
    category: 'strategy',
    description: 'A document issued by the project sponsor that formally authorizes the existence of a project and gives the PM authority to apply organizational resources.',
    createdBy: 'Project sponsor (with input from the PM)',
    whenUsed: 'Created during Initiating. It is the PM\'s source of authority throughout the project.',
    keyPurpose: 'Formally authorizes the project, names the PM, and documents high-level requirements, milestones, budget, and success criteria.',
    examTip: 'The charter is signed by the SPONSOR, not the PM. Without a signed charter, the project cannot proceed. It includes measurable objectives and high-level risks. It is NOT a detailed plan.',
    relatedTo: ['Business Case', 'Stakeholder Register', 'Assumption Log'],
    domains: ['Stakeholders', 'Planning', 'Dev Approach and Life Cycle'],
  },
  {
    id: 'project-vision',
    name: 'Project Vision Statement',
    category: 'strategy',
    description: 'A concise, high-level description of the project that states the purpose and inspires the team to contribute.',
    createdBy: 'Project sponsor or PM',
    whenUsed: 'Created during Initiating. Used to align the team around a shared goal.',
    keyPurpose: 'Provides direction and motivation — the "north star" for the project team.',
    examTip: 'Common in agile projects. Think of it as the elevator pitch for the project.',
    relatedTo: ['Project Charter', 'Roadmap'],
    domains: ['Stakeholders', 'Team'],
  },
  {
    id: 'roadmap',
    name: 'Roadmap',
    category: 'strategy',
    description: 'A high-level timeline that depicts milestones, significant events, reviews, and decision points.',
    createdBy: 'PM and project team',
    whenUsed: 'Created during Planning. Used to communicate the big picture timeline to stakeholders.',
    keyPurpose: 'Gives stakeholders a strategic view of when major deliverables and milestones will occur.',
    examTip: 'A roadmap is NOT a detailed schedule. It shows themes and milestones at a high level. Common in both predictive and agile projects.',
    relatedTo: ['Project Charter', 'Project Schedule', 'Milestone List'],
    domains: ['Planning', 'Stakeholders'],
  },

  // ─── LOGS & REGISTERS ─────────────────────────────────────────
  {
    id: 'assumption-log',
    name: 'Assumption Log',
    category: 'logs',
    description: 'Records all assumptions and constraints throughout the project. Assumptions are factors considered true without proof; constraints limit options.',
    createdBy: 'PM and project team',
    whenUsed: 'Created during Initiating (with the charter). Updated continuously throughout the project.',
    keyPurpose: 'Tracks what we\'re assuming to be true and what limits us. Unvalidated assumptions become risks.',
    examTip: 'Created during Develop Project Charter — one of the earliest artifacts. If an assumption proves false, it often triggers a risk response or change request.',
    relatedTo: ['Risk Register', 'Project Charter'],
    domains: ['Planning', 'Uncertainty'],
  },
  {
    id: 'stakeholder-register',
    name: 'Stakeholder Register',
    category: 'logs',
    description: 'Records information about project stakeholders including assessment, classification, engagement level, and influence.',
    createdBy: 'PM',
    whenUsed: 'Created during Initiating. Updated throughout the project as new stakeholders are identified.',
    keyPurpose: 'Documents who the stakeholders are, their interests, influence, and engagement strategy.',
    examTip: 'Stakeholder identification is CONTINUOUS — not a one-time activity. The register should be updated regularly. Contains power/interest/influence assessments.',
    relatedTo: ['Project Charter', 'Communications Management Plan', 'Stakeholder Engagement Plan'],
    domains: ['Stakeholders', 'Team', 'Planning'],
  },
  {
    id: 'risk-register',
    name: 'Risk Register',
    category: 'logs',
    description: 'A repository for all identified risks, their probability, impact, risk score, planned responses, owners, and status.',
    createdBy: 'PM and project team',
    whenUsed: 'Created during Planning (Identify Risks). Updated throughout the project as new risks emerge or existing ones change.',
    keyPurpose: 'Central repository for tracking all project risks and their response strategies.',
    examTip: 'The risk register is the OUTPUT of Identify Risks and is updated by ALL other risk processes. It includes risk owners, triggers, and contingency plans. Risks can be threats OR opportunities.',
    relatedTo: ['Risk Management Plan', 'Assumption Log', 'Issue Log'],
    domains: ['Uncertainty', 'Planning', 'Project Work'],
  },
  {
    id: 'issue-log',
    name: 'Issue Log',
    category: 'logs',
    description: 'Records and monitors information on active issues — current conditions that may impact project objectives.',
    createdBy: 'PM',
    whenUsed: 'Created when issues first arise (typically during Executing). Updated continuously.',
    keyPurpose: 'Tracks current problems that need resolution, who is responsible, and target dates.',
    examTip: 'Issues are CURRENT problems (already happened). Risks are POTENTIAL problems (may happen). Don\'t confuse the two. Issues require immediate action.',
    relatedTo: ['Risk Register', 'Change Log'],
    domains: ['Project Work', 'Stakeholders'],
  },
  {
    id: 'change-log',
    name: 'Change Log',
    category: 'logs',
    description: 'A comprehensive list of all change requests submitted during the project and their current status (approved, rejected, deferred).',
    createdBy: 'PM (managed through Integrated Change Control)',
    whenUsed: 'Updated whenever a change request is submitted. Used throughout the project.',
    keyPurpose: 'Documents all changes, their status, and impact. Provides an audit trail.',
    examTip: 'ALL changes go through Integrated Change Control. Even approved changes must be documented. The CCB (Change Control Board) reviews changes, not just the PM.',
    relatedTo: ['Project Management Plan', 'Issue Log'],
    domains: ['Project Work', 'Planning'],
  },
  {
    id: 'lessons-learned',
    name: 'Lessons Learned Register',
    category: 'logs',
    description: 'Records knowledge gained during the project so it can be used to improve future performance.',
    createdBy: 'PM and project team',
    whenUsed: 'Updated THROUGHOUT the project (not just at the end). Formally compiled during Closing.',
    keyPurpose: 'Captures what went well, what didn\'t, and what to do differently. Becomes an organizational process asset.',
    examTip: 'Lessons learned are collected THROUGHOUT the project — this is a common exam trap. Many people think it\'s only done at closing. At closing, they are finalized and archived.',
    relatedTo: ['Organizational Process Assets'],
    domains: ['Project Work', 'Team', 'Delivery'],
  },
  {
    id: 'backlog',
    name: 'Product Backlog',
    category: 'logs',
    description: 'An ordered list of everything that is known to be needed in the product. The single source of work for the team.',
    createdBy: 'Product Owner',
    whenUsed: 'Created at project start in agile/adaptive projects. Continuously refined (groomed) throughout.',
    keyPurpose: 'Prioritized list of features, requirements, and fixes. Drives what gets built in each iteration.',
    examTip: 'The Product Owner owns and prioritizes the backlog — NOT the Scrum Master or PM. Backlog refinement (grooming) is ongoing. Items at the top are most detailed.',
    relatedTo: ['User Stories', 'Sprint Backlog', 'Roadmap'],
    domains: ['Planning', 'Delivery', 'Stakeholders'],
  },

  // ─── PLANS ─────────────────────────────────────────────────────
  {
    id: 'pm-plan',
    name: 'Project Management Plan',
    category: 'plans',
    description: 'The master plan that defines how the project is executed, monitored, controlled, and closed. Contains all subsidiary plans and baselines.',
    createdBy: 'PM and project team',
    whenUsed: 'Developed during Planning. Referenced and updated throughout the entire project.',
    keyPurpose: 'The single source of truth for how the project will be managed. Integrates all subsidiary plans.',
    examTip: 'This is NOT just a schedule! It includes scope, schedule, cost, quality, resource, communications, risk, procurement, and stakeholder management plans PLUS the three baselines.',
    relatedTo: ['All subsidiary plans', 'Scope Baseline', 'Schedule Baseline', 'Cost Baseline'],
    domains: ['Planning', 'Project Work', 'Delivery', 'Measurement'],
  },
  {
    id: 'scope-mgmt-plan',
    name: 'Scope Management Plan',
    category: 'plans',
    description: 'Defines how the project scope will be defined, developed, monitored, controlled, and validated.',
    createdBy: 'PM and project team',
    whenUsed: 'Created during Planning. Guides all scope-related activities.',
    keyPurpose: 'Establishes the process for managing scope — how to handle scope changes and prevent scope creep.',
    examTip: 'The scope management plan does NOT contain the scope itself — it describes the PROCESS for managing scope.',
    relatedTo: ['Requirements Management Plan', 'WBS', 'Scope Baseline'],
    domains: ['Planning'],
  },
  {
    id: 'risk-mgmt-plan',
    name: 'Risk Management Plan',
    category: 'plans',
    description: 'Defines how risk management activities will be structured and performed throughout the project.',
    createdBy: 'PM and project team',
    whenUsed: 'Created during Planning. Guides all risk management processes.',
    keyPurpose: 'Establishes the methodology, roles, budgets, timing, risk categories, and thresholds for risk management.',
    examTip: 'This plan describes HOW to manage risks — not the risks themselves. The risks are in the Risk Register. Risk has the most planning processes (5) of any knowledge area.',
    relatedTo: ['Risk Register', 'Risk Report'],
    domains: ['Uncertainty', 'Planning'],
  },
  {
    id: 'comms-plan',
    name: 'Communications Management Plan',
    category: 'plans',
    description: 'Describes how project communications will be planned, structured, implemented, and monitored.',
    createdBy: 'PM',
    whenUsed: 'Created during Planning. Used throughout to guide all communications.',
    keyPurpose: 'Defines who needs what information, when, how, and how often. Prevents communication gaps.',
    examTip: '90% of PM time is spent communicating. The plan should address stakeholder communication requirements. Remember: channels = n(n-1)/2.',
    relatedTo: ['Stakeholder Register', 'Stakeholder Engagement Plan'],
    domains: ['Stakeholders', 'Planning', 'Project Work'],
  },
  {
    id: 'change-control-plan',
    name: 'Change Control Plan',
    category: 'plans',
    description: 'Describes how change requests are formally managed, including the process, approval authority, and CCB roles.',
    createdBy: 'PM',
    whenUsed: 'Created during Planning. Applied whenever changes are requested.',
    keyPurpose: 'Ensures all changes are formally evaluated, approved/rejected, and documented.',
    examTip: 'All changes must go through Integrated Change Control. Even "small" changes need evaluation. Gold plating (adding unrequested extras) is NOT acceptable.',
    relatedTo: ['Change Log', 'Project Management Plan'],
    domains: ['Project Work', 'Planning'],
  },

  // ─── BASELINES ─────────────────────────────────────────────────
  {
    id: 'scope-baseline',
    name: 'Scope Baseline',
    category: 'baselines',
    description: 'The approved version of the scope statement, WBS, and WBS dictionary. Used to compare actual scope to planned.',
    createdBy: 'PM and project team (approved by sponsor/CCB)',
    whenUsed: 'Established during Planning. Used as the benchmark for scope throughout the project.',
    keyPurpose: 'The approved scope against which all scope changes are measured.',
    examTip: 'The scope baseline includes THREE things: Scope Statement + WBS + WBS Dictionary. Changes to the baseline require formal change control.',
    relatedTo: ['WBS', 'Scope Statement', 'Project Management Plan'],
    domains: ['Planning', 'Measurement'],
  },
  {
    id: 'schedule-baseline',
    name: 'Schedule Baseline',
    category: 'baselines',
    description: 'The approved version of the project schedule used as the basis for comparison with actual results.',
    createdBy: 'PM and project team (approved by sponsor/CCB)',
    whenUsed: 'Established during Planning. Used to measure schedule performance (SV, SPI).',
    keyPurpose: 'The approved schedule against which progress is tracked.',
    examTip: 'Part of the Performance Measurement Baseline (PMB) along with scope and cost baselines. EVM calculations use the schedule baseline for Planned Value (PV).',
    relatedTo: ['Project Schedule', 'Scope Baseline', 'Cost Baseline'],
    domains: ['Planning', 'Measurement'],
  },
  {
    id: 'cost-baseline',
    name: 'Cost Baseline',
    category: 'baselines',
    description: 'The approved version of the time-phased project budget, excluding management reserves.',
    createdBy: 'PM and project team (approved by sponsor/CCB)',
    whenUsed: 'Established during Planning. Used to measure cost performance (CV, CPI).',
    keyPurpose: 'The approved budget against which spending is tracked. BAC comes from the cost baseline.',
    examTip: 'Cost Baseline + Management Reserves = Project Budget. The cost baseline is the BAC (Budget at Completion) used in all EVM formulas.',
    relatedTo: ['Schedule Baseline', 'Scope Baseline', 'Budget'],
    domains: ['Planning', 'Measurement'],
  },

  // ─── VISUAL & DATA ─────────────────────────────────────────────
  {
    id: 'wbs',
    name: 'Work Breakdown Structure (WBS)',
    category: 'visual',
    description: 'A hierarchical decomposition of the total scope of work to be carried out by the team. Each level provides greater detail.',
    createdBy: 'PM and project team',
    whenUsed: 'Created during Planning (Create WBS process). Referenced throughout the project.',
    keyPurpose: 'Organizes and defines the total scope. Work packages at the lowest level are used for estimating, scheduling, and assigning work.',
    examTip: 'The WBS shows DELIVERABLES, not activities. The lowest level is called a "work package." The WBS is part of the scope baseline. If it\'s not in the WBS, it\'s not in the project.',
    relatedTo: ['Scope Baseline', 'WBS Dictionary', 'Activity List'],
    domains: ['Planning', 'Delivery'],
  },
  {
    id: 'network-diagram',
    name: 'Schedule Network Diagram',
    category: 'visual',
    description: 'A graphical representation of the logical relationships (dependencies) among project activities.',
    createdBy: 'PM and project team',
    whenUsed: 'Created during Planning (Sequence Activities). Used for critical path analysis.',
    keyPurpose: 'Shows the order in which activities must be performed and identifies the critical path.',
    examTip: 'Used to find the Critical Path (longest path = shortest project duration). Know the four dependency types: FS (most common), FF, SS, SF (rare).',
    relatedTo: ['Activity List', 'Project Schedule', 'Critical Path'],
    domains: ['Planning'],
  },
  {
    id: 'raci-matrix',
    name: 'RACI / Responsibility Assignment Matrix',
    category: 'visual',
    description: 'A chart showing who is Responsible, Accountable, Consulted, and Informed for each work package or activity.',
    createdBy: 'PM',
    whenUsed: 'Created during Planning. Referenced throughout for role clarity.',
    keyPurpose: 'Clarifies roles and eliminates ambiguity about who does what.',
    examTip: 'Only ONE person can be Accountable (the "A") for each item. Multiple people can be Responsible. The PM is often Accountable for overall project delivery.',
    relatedTo: ['Resource Management Plan', 'WBS'],
    domains: ['Team', 'Planning'],
  },
  {
    id: 'burndown',
    name: 'Burndown / Burnup Chart',
    category: 'visual',
    description: 'A graphical representation of work remaining (burndown) or work completed (burnup) versus time in an iteration or project.',
    createdBy: 'Scrum Master or PM',
    whenUsed: 'Updated daily during sprints/iterations. Used in agile/adaptive projects.',
    keyPurpose: 'Shows at a glance whether the team is on track to complete planned work within the timebox.',
    examTip: 'Burndown goes DOWN to zero (work remaining). Burnup goes UP to the total (work completed). Both show progress against plan.',
    relatedTo: ['Product Backlog', 'Sprint Backlog', 'Velocity'],
    domains: ['Measurement', 'Delivery'],
  },

  // ─── OTHER KEY DOCUMENTS ───────────────────────────────────────
  {
    id: 'work-perf-data',
    name: 'Work Performance Data',
    category: 'other',
    description: 'Raw observations and measurements identified during activities — the "raw facts" about project work.',
    createdBy: 'Project team',
    whenUsed: 'Generated during Executing as work is performed.',
    keyPurpose: 'Raw data (e.g., % complete, actual costs, actual dates) that gets analyzed into useful information.',
    examTip: 'Data → Information → Reports. Work Performance DATA is raw. Work Performance INFORMATION is analyzed. Work Performance REPORTS are formatted for stakeholders.',
    relatedTo: ['Work Performance Information', 'Work Performance Reports'],
    domains: ['Project Work', 'Measurement'],
  },
  {
    id: 'deliverables',
    name: 'Deliverables',
    category: 'other',
    description: 'Any unique and verifiable product, result, or capability to perform a service that is produced to complete a process, phase, or project.',
    createdBy: 'Project team',
    whenUsed: 'Produced during Executing. Verified during M&C (Validate Scope).',
    keyPurpose: 'The tangible outputs of the project that the project was initiated to produce.',
    examTip: 'Deliverables are verified by Quality Control FIRST, then formally accepted by the customer/sponsor through Validate Scope. Both must happen.',
    relatedTo: ['WBS', 'Scope Baseline', 'Quality Control'],
    domains: ['Delivery', 'Project Work'],
  },
  {
    id: 'opa',
    name: 'Organizational Process Assets (OPAs)',
    category: 'other',
    description: 'Plans, processes, policies, procedures, and knowledge bases specific to the organization that can be used on the project.',
    createdBy: 'The performing organization (accumulated over time)',
    whenUsed: 'Used as inputs throughout the project. Updated at project closing with lessons learned.',
    keyPurpose: 'Provides the PM with historical information, templates, and organizational knowledge to guide project decisions.',
    examTip: 'OPAs include lessons learned from PAST projects, templates, and procedures. They are INTERNAL to the organization. Don\'t confuse with Enterprise Environmental Factors (EEFs), which are external conditions.',
    relatedTo: ['Lessons Learned Register', 'Enterprise Environmental Factors'],
    domains: ['Planning', 'Project Work'],
  },
  {
    id: 'eef',
    name: 'Enterprise Environmental Factors (EEFs)',
    category: 'other',
    description: 'Conditions not under the immediate control of the project team that influence, constrain, or direct the project.',
    createdBy: 'External to the project (organizational culture, market conditions, regulations, etc.)',
    whenUsed: 'Considered as inputs throughout the project. Cannot be changed by the PM.',
    keyPurpose: 'Context the PM must work within — the "hand you\'re dealt."',
    examTip: 'EEFs include: organizational culture, government regulations, market conditions, political climate, stakeholder risk tolerance. OPAs are internal; EEFs are external conditions.',
    relatedTo: ['Organizational Process Assets'],
    domains: ['Planning', 'Project Work', 'Stakeholders'],
  },
]
