-- Replace the twenty structural exemplars with scenario-specific answer sets.
-- All items remain REVIEW and require independent content and difficulty approval.

with revised(item_code, options, answer_key, rationale_correct, rationale_distractors, eco_task_code) as (
values
('People-1','[{"id":"A","text":"Facilitate the specialists in identifying the conflict source, agreeing ownership criteria, and selecting a resolution."},{"id":"B","text":"Assign the task to the specialist with the longest organizational tenure."},{"id":"C","text":"Split the task equally even if the integration work cannot be separated."},{"id":"D","text":"Escalate both specialists to their functional managers before discussing the disagreement."}]'::jsonb,'A','Addressing the source and agreeing a resolution restores ownership while preserving team accountability.','{"B":"Tenure is not evidence of the appropriate integration responsibility.","C":"An arbitrary split can create unclear interfaces and duplicate accountability.","D":"Immediate escalation bypasses a conflict the team can first resolve collaboratively."}'::jsonb,'PPL-2'),
('People-2','[{"id":"A","text":"Reject every request that did not enter through the agreed channel."},{"id":"B","text":"Meet the stakeholder, clarify the value and urgency, and agree how future requests will be evaluated and prioritized."},{"id":"C","text":"Tell team members to ignore the stakeholder without further discussion."},{"id":"D","text":"Accept the urgent work and revise iteration commitments after delivery."}]'::jsonb,'B','Direct engagement protects the relationship while restoring transparent prioritization and team focus.','{"A":"Automatic rejection may discard value and damages engagement.","C":"Avoidance leaves the stakeholder expectation and governance problem unresolved.","D":"Accepting disruption normalizes bypassing the agreed prioritization process."}'::jsonb,'PPL-4'),
('People-3','[{"id":"A","text":"Reassign all unfamiliar work and permanently narrow the person’s responsibilities."},{"id":"B","text":"Wait for the person to request help because raising performance concerns may reduce trust."},{"id":"C","text":"Hold a private conversation, identify the capability gap, and agree coaching or pairing support with checkpoints."},{"id":"D","text":"Recognize the colleagues who are completing the unfinished work and maintain the arrangement."}]'::jsonb,'C','Private diagnosis and supported development address performance and psychological safety without hiding the gap.','{"A":"Permanent reassignment avoids development and may waste capability.","B":"Waiting allows delivery and wellbeing risks to grow.","D":"The workaround conceals the cause and overloads other team members."}'::jsonb,'PPL-3'),
('People-4','[{"id":"A","text":"Require every participant to speak for the same number of minutes."},{"id":"B","text":"Ask the two experienced members to approve decisions after each meeting."},{"id":"C","text":"Move all decisions to asynchronous voting without discussion."},{"id":"D","text":"Use inclusive facilitation, varied participation channels, and explicit invitations for relevant expertise."}]'::jsonb,'D','Multiple inclusive participation mechanisms surface relevant perspectives without imposing artificial equality.','{"A":"Equal airtime does not ensure relevant or psychologically safe contribution.","B":"Concentrating approval reinforces the imbalance.","C":"Voting alone removes context-building and can preserve silence."}'::jsonb,'PPL-3'),
('People-5','[{"id":"A","text":"Reframe the disagreement around shared release outcomes, evidence, risk tolerance, and agreed decision authority."},{"id":"B","text":"Support the product owner because customer value always overrides technical concerns."},{"id":"C","text":"Support the technical lead because quality concerns always prevent release."},{"id":"D","text":"Delay the decision until the personal conflict disappears on its own."}]'::jsonb,'A','Shared criteria and decision authority separate the relationship conflict from the evidence-based release decision.','{"B":"One role does not automatically override legitimate technical evidence.","C":"Technical concern must be evaluated against value and risk rather than treated as absolute.","D":"Delay does not manage the conflict or protect the decision window."}'::jsonb,'PPL-2'),
('People-6','[{"id":"A","text":"Continue until resources are withdrawn because the plan remains approved."},{"id":"B","text":"Engage the new manager, reconfirm benefits and priorities, and negotiate the required resource commitments."},{"id":"C","text":"Replace the specialists immediately with external contractors."},{"id":"D","text":"Ask the sponsor to overrule the manager before learning their concerns."}]'::jsonb,'B','Early engagement aligns expectations and tests resource assumptions before escalation or replacement.','{"A":"An approved plan does not remove a newly material resource risk.","C":"Replacement is premature before availability and alternatives are understood.","D":"Premature escalation may entrench resistance and lacks an informed basis."}'::jsonb,'PPL-4'),
('People-7','[{"id":"A","text":"Continue making routine decisions so the team can protect its delivery record."},{"id":"B","text":"Require sponsor approval for all decisions as complexity increases."},{"id":"C","text":"Clarify decision boundaries, delegate appropriate authority, and coach the team as it assumes ownership."},{"id":"D","text":"Rotate the project-manager role among team members each iteration."}]'::jsonb,'C','Clear delegated authority builds autonomy while retaining governance for decisions outside team boundaries.','{"A":"Central dependence is the identified constraint and will worsen with complexity.","B":"Additional centralization slows decisions further.","D":"Role rotation is disproportionate and does not define authority."}'::jsonb,'PPL-3'),
('People-8','[{"id":"A","text":"Reduce the stakeholder’s access to project information until implementation."},{"id":"B","text":"Ask the sponsor to direct the stakeholder to support the approved workflow."},{"id":"C","text":"Continue the engagement plan because the stakeholder was previously supportive."},{"id":"D","text":"Meet the stakeholder to understand the impact, address concerns, and involve affected users in the transition approach."}]'::jsonb,'D','Understanding impact and involving affected people supports alignment, trust, and adoption before resistance spreads.','{"A":"Withholding information increases uncertainty and mistrust.","B":"Authority may force compliance but does not build adoption.","C":"Changed stakeholder conditions require the engagement plan to be adapted."}'::jsonb,'PPL-5'),
('Process-1','[{"id":"A","text":"Model the approval-duration uncertainty, engage the regulator early, and incorporate response options into the integrated plan."},{"id":"B","text":"Use the shortest historical approval duration to protect the contractual date."},{"id":"C","text":"Remove regulatory review from the schedule because its duration is externally controlled."},{"id":"D","text":"Add the longest historical duration as fixed contingency without further analysis."}]'::jsonb,'A','Integrated uncertainty analysis and early engagement create realistic options while preserving compliance.','{"B":"Optimistic selection hides material schedule exposure.","C":"External work still constrains the project and must be represented.","D":"A single worst-case assumption may distort the plan without assessing probability or responses."}'::jsonb,'PRC-1'),
('Process-2','[{"id":"A","text":"Release because satisfying acceptance criteria proves that value was delivered."},{"id":"B","text":"Review the outcome evidence with the product owner and users, then adapt or stop the feature based on expected value."},{"id":"C","text":"Add more features before reassessing the original user problem."},{"id":"D","text":"Reject the iteration because the team followed the approved design."}]'::jsonb,'B','Acceptance confirms conformance, while outcome evidence determines whether continued investment delivers value.','{"A":"Conformance is not the same as solving the user problem.","C":"More output compounds waste before the value assumption is tested.","D":"Blaming the iteration does not guide a value-based response."}'::jsonb,'PRC-3'),
('Process-3','[{"id":"A","text":"Move the contractual milestone by three weeks immediately."},{"id":"B","text":"Terminate the supplier before requesting recovery information."},{"id":"C","text":"Obtain the recovery plan and analyze dependency, resequencing, cost, and risk impacts before recommending action."},{"id":"D","text":"Direct downstream teams to increase overtime until the component arrives."}]'::jsonb,'C','A verified recovery plan and integrated impact analysis are necessary before selecting a schedule response.','{"A":"The supplier delay may not translate directly into the same milestone delay.","B":"Termination is premature and may worsen the constraint.","D":"Overtime does not resolve work blocked by the missing component."}'::jsonb,'PRC-8'),
('Process-4','[{"id":"A","text":"Remove the approval meetings because stable velocity proves governance is unnecessary."},{"id":"B","text":"Increase iteration length so approvals occur less frequently."},{"id":"C","text":"Route every increment directly to senior management."},{"id":"D","text":"Map approval needs and thresholds, then tailor evidence and review timing to preserve control with faster flow."}]'::jsonb,'D','Tailoring governance to risk and evidence maintains accountability while removing avoidable delay.','{"A":"Velocity does not eliminate governance obligations.","B":"Longer iterations can delay value and feedback without fixing approval flow.","C":"Universal escalation increases delay and weakens delegated governance."}'::jsonb,'PRC-9'),
('Process-5','[{"id":"A","text":"Perform root-cause analysis with relevant stakeholders, clarify the requirement, and update quality controls to prevent recurrence."},{"id":"B","text":"Repair only the defects already found to protect contingency."},{"id":"C","text":"Lower the defect threshold because interpretations differ."},{"id":"D","text":"Postpone requirement clarification until the release retrospective."}]'::jsonb,'A','Correcting the shared cause and prevention controls protects both current quality and remaining contingency.','{"B":"Instance repair leaves the systemic source active.","C":"Changing tolerance does not resolve requirement ambiguity.","D":"Deferral permits additional avoidable defects."}'::jsonb,'PRC-7'),
('Process-6','[{"id":"A","text":"Commit the existing backlog because it was previously prioritized."},{"id":"B","text":"Validate the new evidence with the product owner and customers, then reprioritize work by expected value."},{"id":"C","text":"Add the new need without removing or delaying any planned work."},{"id":"D","text":"Ignore interviews until usage data is available after release."}]'::jsonb,'B','Current customer evidence should inform value-based prioritization before the next commitment.','{"A":"Earlier priorities may no longer maximize value.","C":"Adding work without trade-offs ignores capacity and opportunity cost.","D":"Waiting discards timely evidence that can prevent low-value delivery."}'::jsonb,'PRC-3'),
('Process-7','[{"id":"A","text":"Begin the work because sponsor support constitutes approval."},{"id":"B","text":"Ask vendors to absorb all impacts before documenting the request."},{"id":"C","text":"Analyze integrated impacts and submit the request through the established change-control authority."},{"id":"D","text":"Reject the change because it affects baselines and contracts."}]'::jsonb,'C','Integrated analysis enables the authorized body to decide transparently across value, baselines, and contracts.','{"A":"Sponsor advocacy may not equal authorized change approval.","B":"Contract impacts require analysis and negotiation, not unilateral transfer.","D":"Potential impact is a reason to evaluate, not automatically reject, value."}'::jsonb,'PRC-2'),
('Process-8','[{"id":"A","text":"Use software velocity as the single program measure."},{"id":"B","text":"Use construction schedule variance as the single program measure."},{"id":"C","text":"Ask each team to report independently and compare reports after the milestone."},{"id":"D","text":"Map the changed dependency into an integrated plan and evaluate effects using shared milestone and value measures."}]'::jsonb,'D','An integrated dependency view translates different delivery measures into a common impact assessment.','{"A":"Velocity alone cannot represent construction dependency impact.","B":"Schedule variance alone omits software delivery and value evidence.","C":"Separate delayed reporting preserves the information gap."}'::jsonb,'PRC-1'),
('Process-9','[{"id":"A","text":"Reconcile source data, validate metric definitions, and present the variance with its decision impact."},{"id":"B","text":"Publish the more favorable dashboard because stakeholders need confidence."},{"id":"C","text":"Average the conflicting figures without investigating their definitions."},{"id":"D","text":"Stop status reporting until both systems produce identical values."}]'::jsonb,'A','Reconciliation and transparent impact reporting restore a reliable basis for governance decisions.','{"B":"Selective reporting misrepresents status and undermines trust.","C":"Averaging incompatible measures creates a meaningless result.","D":"Withholding status removes timely governance information."}'::jsonb,'PRC-9'),
('Process-10','[{"id":"A","text":"Reject all support requests during iterations."},{"id":"B","text":"Analyze demand and capacity with stakeholders, then establish an explicit service policy and protect product commitments."},{"id":"C","text":"Increase velocity targets without changing capacity or intake."},{"id":"D","text":"Carry unfinished work forward indefinitely because support creates customer value."}]'::jsonb,'B','An explicit capacity and service policy makes value trade-offs visible and restores feasible commitments.','{"A":"A blanket rejection ignores legitimate service value.","C":"A higher target does not remove unplanned demand.","D":"Unlimited carryover hides the constraint and erodes predictability."}'::jsonb,'PRC-1'),
('Business-1','[{"id":"A","text":"Continue unchanged because the deliverables met requirements when approved."},{"id":"B","text":"Implement every possible compliance change before confirming applicability."},{"id":"C","text":"Confirm obligations, assess compliance and business impacts, and route necessary changes through governance."},{"id":"D","text":"Transfer compliance ownership entirely to the sponsor."}]'::jsonb,'C','Current obligations and consequences must be established before an authorized, proportionate response is selected.','{"A":"Compliance exposure can change during the project.","B":"Unverified changes may waste resources or introduce new risk.","D":"The project manager still coordinates compliance analysis and action."}'::jsonb,'BEN-2'),
('Business-2','[{"id":"A","text":"Close the project because planned capabilities were delivered."},{"id":"B","text":"Declare benefits achieved because the service is technically available."},{"id":"C","text":"Extend the project indefinitely until forecast adoption occurs."},{"id":"D","text":"Review adoption barriers and benefits evidence with operations and governance, then agree transition and enablement actions."}]'::jsonb,'D','Coordinated evidence and transition action connect delivered capability to sustainable organizational outcomes.','{"A":"Technical completion alone does not establish readiness for benefits realization.","B":"Availability is not evidence of adoption or realized value.","C":"An indefinite extension avoids a governed transition decision."}'::jsonb,'BEN-7')
)
update public.diagnostic_items d set
  options = r.options,
  key = r.answer_key,
  rationale_correct = r.rationale_correct,
  rationale_distractors = r.rationale_distractors,
  eco_task_code = r.eco_task_code,
  reviewed_by = null,
  status = 'review',
  authored_by = 'PMPeco bespoke remediation — pending independent SME review',
  updated_at = now()
from revised r
where d.track_id = 'pmbok8' and d.eco_task = r.item_code and d.version = 1;

-- Process-9 is rewritten as project-status evaluation so its Process-domain tag is valid.
update public.diagnostic_items set stem =
  'Two project dashboards show conflicting completion and forecast figures because the delivery teams use different data cutoffs and definitions. Governance will decide funding at tomorrow’s review, and both team leads insist their report is correct. The underlying records are available for comparison. What should the project manager do first to provide a reliable project status?'
where track_id = 'pmbok8' and eco_task = 'Process-9' and version = 1;

-- Map the twelve bespoke expansion items and correct judgement-item cognitive tags.
update public.diagnostic_items set eco_task_code = case eco_task
  when 'People-9' then 'PPL-3' when 'People-10' then 'PPL-2' when 'People-11' then 'PPL-3'
  when 'Process-11' then 'PRC-2' when 'Process-12' then 'PRC-5' when 'Process-13' then 'PRC-8'
  when 'Business-3' then 'BEN-2' when 'Business-4' then 'BEN-1' when 'Business-5' then 'BEN-2'
  when 'Business-6' then 'BEN-7' when 'Business-7' then 'BEN-8' when 'Business-8' then 'BEN-8'
end,
cognitive_level = case
  when eco_task = 'People-9' then 'application'
  when eco_task in ('Process-11','Business-3') then 'analysis'
  else cognitive_level
end,
status = 'review'
where track_id = 'pmbok8' and version = 1 and eco_task in (
  'People-9','People-10','People-11','Process-11','Process-12','Process-13',
  'Business-3','Business-4','Business-5','Business-6','Business-7','Business-8'
);

notify pgrst, 'reload schema';
