-- Add sixteen independently reviewable reserve items, producing a 48-item pool.
-- Pool targets: domains 16/20/12; approaches 19/15/14; difficulty 12/24/12.

with item(code, stem, options, key, domain, approach, eco_task_code, cognitive_level, difficulty_b,
          rationale_correct, rationale_distractors) as (values
('Reserve-01','A hybrid program has technically successful teams but different interpretations of the outcome they are collectively pursuing. Local priorities are beginning to compete, and leaders are requesting more detailed schedules. What should the program manager facilitate first to restore coherent decisions?',
'[{"id":"A","text":"Create a shared outcome statement with stakeholders and connect team objectives and measures to it."},{"id":"B","text":"Publish one detailed schedule for every team regardless of delivery approach."},{"id":"C","text":"Allow each team to define success independently until integration."},{"id":"D","text":"Escalate every priority conflict to the steering committee."}]'::jsonb,'A','people','hybrid','PPL-1','analysis',0.0,'A shared, current vision provides the decision frame needed before plans are made more detailed.','{"B":"Schedule detail cannot resolve conflicting interpretations of success.","C":"Independent definitions defer and amplify integration conflict.","D":"Routine alignment belongs with the program before governance escalation."}'::jsonb),
('Reserve-02','An agile team depends on one architect who is leaving after the next iteration. Documentation is incomplete, and other members avoid architecture decisions because they fear making mistakes. Delivery can continue briefly. What is the best action for the project manager to support sustainable knowledge transfer?',
'[{"id":"A","text":"Ask the architect to document everything alone during the final week."},{"id":"B","text":"Pair team members with the architect on real decisions and capture validated knowledge as they work."},{"id":"C","text":"Delay all architecture decisions until a replacement is hired."},{"id":"D","text":"Transfer ownership to the most senior developer without preparation."}]'::jsonb,'B','people','agile','PPL-7','application',0.1,'Pairing transfers tacit and explicit knowledge while demonstrating competence in context.','{"A":"Documents alone rarely capture decision reasoning or build capability.","C":"Delay increases dependence and may interrupt delivery.","D":"Seniority does not substitute for deliberate knowledge transfer."}'::jsonb),
('Reserve-03','A predictive project must report monthly to regulators, weekly to the sponsor, and daily operational exceptions to a control team. Stakeholders complain about duplicated reports and missed critical information. What should the project manager do next when defining the communication approach?',
'[{"id":"A","text":"Send the same detailed report to every stakeholder."},{"id":"B","text":"Stop daily reporting because monthly reporting is mandatory."},{"id":"C","text":"Map information, timing, format, ownership, and feedback needs for each audience."},{"id":"D","text":"Ask stakeholders to retrieve raw project data whenever needed."}]'::jsonb,'C','people','predictive','PPL-8','application',-0.8,'Audience-specific information and feedback requirements prevent duplication while preserving governance needs.','{"A":"Identical detail does not fit different decisions and cadences.","B":"Mandatory monthly reporting does not replace operational exception handling.","D":"Raw-data access transfers interpretation risk and may not satisfy reporting obligations."}'::jsonb),
('Reserve-04','An agile product sponsor expects every requested feature in the release, while users prioritize reliability and the team identifies capacity limits. The release date is fixed. What is the best action for the project manager to align expectations without promising an infeasible outcome?',
'[{"id":"A","text":"Commit to all sponsor requests and ask the team to improve velocity."},{"id":"B","text":"Let users decide alone because they operate the product."},{"id":"C","text":"Move the release date without consulting governance."},{"id":"D","text":"Facilitate transparent trade-offs using capacity, value, reliability, and release constraints."}]'::jsonb,'D','people','agile','PPL-5','analysis',0.8,'Evidence-based trade-offs create an achievable shared expectation among competing stakeholder needs.','{"A":"An unsupported commitment hides the capacity constraint.","B":"Users are important but do not solely own investment and release decisions.","C":"Unilateral date change bypasses stakeholder and governance authority."}'::jsonb),
('Reserve-05','A predictive project adds a community group as a stakeholder after site work has started. The group has legitimate concerns but receives technical reports it cannot interpret and is becoming distrustful. What should the project manager do next to improve engagement?',
'[{"id":"A","text":"Tailor communication to the group’s concerns and literacy, establish dialogue, and update the engagement plan."},{"id":"B","text":"Continue the approved technical reporting format to ensure consistency."},{"id":"C","text":"Ask the sponsor to speak for the community group."},{"id":"D","text":"Limit engagement until the group submits formal objections."}]'::jsonb,'A','people','predictive','PPL-4','application',0.0,'Tailored two-way communication builds understanding and incorporates the newly identified stakeholder.','{"B":"Consistency is ineffective when the audience cannot use the information.","C":"The sponsor cannot replace direct engagement with affected stakeholders.","D":"Waiting turns manageable concerns into avoidable resistance."}'::jsonb),
('Reserve-06','A predictive project needs a scarce testing facility shared with two higher-priority programs. The baseline assumes uninterrupted access, but the portfolio office confirms only partial availability. Several critical activities depend on the facility. What should the project manager do first to create a feasible resource plan?',
'[{"id":"A","text":"Retain the baseline and record the shortage as an issue."},{"id":"B","text":"Analyze demand, constraints, alternatives, and integrated schedule impacts, then negotiate access."},{"id":"C","text":"Purchase a new facility without a business case."},{"id":"D","text":"Ask the test team to compress every activity."}]'::jsonb,'B','process','predictive','PRC-4','application',0.0,'Integrated resource and schedule analysis supports a feasible negotiation and proportionate alternatives.','{"A":"Documenting an infeasible assumption does not resolve it.","C":"Major acquisition requires evaluated need, value, and authority.","D":"Universal compression ignores technical feasibility and risk."}'::jsonb),
('Reserve-07','A hybrid project vendor meets delivery dates but repeatedly submits incomplete security evidence required for acceptance. Teams compensate manually, and the relationship remains cooperative. Payment approval is approaching and the requirement is contractually explicit. What is the best next action for the project manager under the procurement agreement?',
'[{"id":"A","text":"Accept all deliverables because operational dates were achieved."},{"id":"B","text":"Terminate the agreement immediately for repeated incompleteness."},{"id":"C","text":"Document performance, enforce the evidence requirement, and agree a time-bound corrective plan."},{"id":"D","text":"Remove the security evidence requirement from future acceptance."}]'::jsonb,'C','process','hybrid','PRC-5','analysis',0.8,'Contract-based performance management and corrective action protect acceptance while preserving a recoverable supplier relationship.','{"A":"Schedule performance does not waive security acceptance obligations.","B":"Immediate termination may be disproportionate before contractual remedies.","D":"Removing a valid requirement creates compliance exposure."}'::jsonb),
('Reserve-08','A predictive project’s forecast shows that currency movement will exceed the existing contingency if current purchasing dates remain unchanged. The exposure is within a governance threshold but is increasing. What should the project manager do next to manage project finance?',
'[{"id":"A","text":"Use management reserve without informing governance."},{"id":"B","text":"Delay recording the variance until invoices are paid."},{"id":"C","text":"Reduce quality spending by the forecast amount."},{"id":"D","text":"Quantify the exposure, evaluate timing or hedging responses, and report through the defined threshold process."}]'::jsonb,'D','process','predictive','PRC-6','application',-0.8,'Forecasting and governed response evaluation address the financial exposure before it becomes an uncontrolled variance.','{"A":"Reserve use requires appropriate authority and transparency.","B":"Waiting removes response time and misstates the forecast.","C":"Arbitrary quality reduction creates unrelated delivery risk."}'::jsonb),
('Reserve-09','An agile team’s automated tests pass, but customers report intermittent failures under real workload patterns. The team proposes adding more features while operations requests stabilization. The failures affect an important customer journey and are reproducible from support data. What should the project manager encourage first to optimize product quality?',
'[{"id":"A","text":"Reproduce the workload conditions, identify the quality gap, and adapt acceptance and testing practices."},{"id":"B","text":"Continue feature delivery because automated tests define acceptance."},{"id":"C","text":"Ask operations to handle failures after each release."},{"id":"D","text":"Stop all development indefinitely until no defect can occur."}]'::jsonb,'A','process','agile','PRC-7','application',0.1,'Evidence from actual use should update quality requirements and prevention controls.','{"B":"Existing tests may omit the conditions that matter to customers.","C":"Operational repair does not correct the development quality gap.","D":"Zero-defect certainty is unrealistic and an indefinite stop is disproportionate."}'::jsonb),
('Reserve-10','A predictive project can recover a milestone by overlapping design and construction, but doing so may increase rework and safety-review complexity. Executives demand a recovery commitment today. What is the best response by the project manager before changing the schedule?',
'[{"id":"A","text":"Overlap all work because the milestone is contractually important."},{"id":"B","text":"Refuse schedule recovery because overlap always creates unacceptable risk."},{"id":"C","text":"Analyze dependencies, rework and safety risks, then seek approval for a supported recovery option."},{"id":"D","text":"Remove safety reviews from the critical path."}]'::jsonb,'C','process','predictive','PRC-8','analysis',0.8,'Schedule compression requires integrated feasibility, risk, and authorization rather than a date-only decision.','{"A":"Importance does not make unsafe or infeasible overlap acceptable.","B":"Overlap can be viable when risks and dependencies support it.","D":"Safety controls cannot be discarded to manufacture schedule recovery."}'::jsonb),
('Reserve-11','A hybrid project is approaching handover. Operations attended demonstrations but has not accepted support ownership, several vendor warranties are undocumented, and the sponsor wants the team released this week. What should the project manager do next before closing the project?',
'[{"id":"A","text":"Close because demonstrations constitute operational acceptance."},{"id":"B","text":"Validate transition criteria, ownership, documentation, and outstanding closure obligations with stakeholders."},{"id":"C","text":"Release the team and ask operations to resolve missing items."},{"id":"D","text":"Extend the project for a fixed six months regardless of remaining work."}]'::jsonb,'B','process','hybrid','PRC-10','application',0.0,'Closure follows verified transition readiness and completed obligations, not schedule pressure alone.','{"A":"Participation does not equal formal readiness or ownership acceptance.","C":"Premature release transfers unresolved risk without agreement.","D":"An arbitrary extension is not based on closure criteria."}'::jsonb),
('Reserve-12','Customer evidence shows that a planned agile feature solves a rare problem, while a smaller alternative would benefit most users and can be released sooner. A senior stakeholder still favors the original feature. What should the project manager encourage first?',
'[{"id":"A","text":"Deliver the original feature because it has senior support."},{"id":"B","text":"Build both options without changing iteration capacity."},{"id":"C","text":"Postpone the decision until all users agree."},{"id":"D","text":"Compare measurable value and feedback, then reprioritize through the product decision process."}]'::jsonb,'D','process','agile','PRC-3','analysis',-0.8,'Transparent value evidence should guide prioritization through the authorized product process.','{"A":"Influence alone does not demonstrate customer value.","B":"Ignoring capacity avoids the required trade-off.","C":"Universal agreement is unnecessary and delays learning."}'::jsonb),
('Reserve-13','A hybrid project receives an approved design change, but one delivery team continues using the previous specification because its local repository was not updated. Other teams have begun rework. What should the project manager do first to control the approved change?',
'[{"id":"A","text":"Reverse the approved change to match the outdated repository."},{"id":"B","text":"Blame the team for failing to monitor governance records."},{"id":"C","text":"Stop affected work, synchronize the approved baseline and communications, and assess rework impacts."},{"id":"D","text":"Allow both specifications until the next governance meeting."}]'::jsonb,'C','business_environment','hybrid','BEN-3','application',0.0,'Immediate synchronization and impact assessment implement the authorized change and limit further rework.','{"A":"A communication failure does not invalidate the authorized decision.","B":"Blame does not stop incorrect work or repair configuration control.","D":"Parallel specifications increase inconsistency and rework."}'::jsonb),
('Reserve-14','An agile team is blocked by a security review queue owned outside the project. Repeated informal requests have not changed priority, and a release with significant customer value is at risk. What is the best next action for the project manager?',
'[{"id":"A","text":"Release without security review because customer value is significant."},{"id":"B","text":"Quantify the impact and use the defined escalation path while collaborating on a feasible review option."},{"id":"C","text":"Tell the team to wait without updating stakeholders."},{"id":"D","text":"Mark the blocked work complete to protect velocity."}]'::jsonb,'B','business_environment','agile','BEN-4','analysis',0.1,'Evidence-based escalation and collaboration apply an intervention without bypassing required control.','{"A":"Value does not authorize bypassing security obligations.","C":"Passive waiting leaves the impediment unmanaged.","D":"Misreporting progress hides rather than removes the blocker."}'::jsonb),
('Reserve-15','A predictive project relies on a sole-source component from a region experiencing escalating trade restrictions. Delivery is still on schedule, but replacement qualification would take months. The next shipment has not yet been committed by the supplier. What should the project manager do first to manage the emerging business risk?',
'[{"id":"A","text":"Wait until a shipment is delayed because the current schedule is intact."},{"id":"B","text":"Cancel the supplier immediately without evaluating alternatives."},{"id":"C","text":"Ask procurement to guarantee that restrictions will not change."},{"id":"D","text":"Analyze exposure and triggers, develop response options, and communicate the risk through governance."}]'::jsonb,'D','business_environment','predictive','BEN-5','analysis',0.8,'Early risk analysis and response planning preserve options before an external threat becomes an issue.','{"A":"Waiting sacrifices the qualification lead time.","B":"Immediate cancellation may create the disruption being avoided.","C":"Procurement cannot guarantee geopolitical conditions."}'::jsonb),
('Reserve-16','A hybrid organization completes retrospectives but the same handover defect appears across projects because lessons remain inside individual team files. Leaders want improvement without adding another reporting ceremony. Existing governance reviews already inspect shared process compliance. What should the project manager community do next?',
'[{"id":"A","text":"Ask each team to conduct longer retrospectives."},{"id":"B","text":"Archive all lessons at project closure for audit purposes."},{"id":"C","text":"Assign responsibility to update the shared process asset and verify adoption through existing reviews."},{"id":"D","text":"Create a new weekly meeting for every project employee."}]'::jsonb,'C','business_environment','hybrid','BEN-6','application',-0.8,'Embedding an owned improvement in shared process assets and existing reviews converts lessons into organizational change.','{"A":"More discussion does not ensure cross-project adoption.","B":"Archiving without integration does not improve practice.","D":"A broad new ceremony adds cost without targeting the adoption mechanism."}'::jsonb)
)
insert into public.diagnostic_items (
  track_id, stem, options, key, domain, approach, eco_task, eco_task_code,
  cognitive_level, rationale_correct, rationale_distractors, readability_grade,
  difficulty_b, status, authored_by, version
)
select 'pmbok8', stem, options, key, domain, approach, code, eco_task_code,
  cognitive_level, rationale_correct, rationale_distractors, 10.0,
  difficulty_b, 'review', 'PMPeco reserve bank — pending independent SME review', 1
from item
where not exists (
  select 1 from public.diagnostic_items d
  where d.track_id = 'pmbok8' and d.eco_task = item.code and d.version = 1
);

do $$
declare d record;
begin
  select count(*) total,
    count(*) filter (where domain='people') people,
    count(*) filter (where domain='process') process,
    count(*) filter (where domain='business_environment') business,
    count(*) filter (where approach='predictive') predictive,
    count(*) filter (where approach='agile') agile,
    count(*) filter (where approach='hybrid') hybrid,
    count(*) filter (where difficulty_b < -0.5) below,
    count(*) filter (where difficulty_b between -0.5 and 0.5) average,
    count(*) filter (where difficulty_b > 0.5) above
  into d from public.diagnostic_items where track_id='pmbok8' and version=1 and status='review';
  if (d.total,d.people,d.process,d.business) <> (48,16,20,12)
    or (d.predictive,d.agile,d.hybrid) <> (19,15,14)
    or (d.below,d.average,d.above) <> (12,24,12) then
    raise exception '48-item reserve pool does not satisfy its design targets';
  end if;
end $$;

notify pgrst, 'reload schema';
